apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-deployment
  labels:
    app: cw2-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: devops-server
  template:
    metadata:
      labels:
        app: devops-server
    spec:
      containers:
        - name: devops-server
          image: samarthuk/cw2-server:v0
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 30
